### ISSUE TITLE
Check requirements packages security 

### ISSUE THREAD

**Issue by xtornasol512** [Prescrypto/WPCI#3]
Checar que paquete necesita o renovarse o quitarlo por esta advertencia
<img width="1070" alt="screen shot 2018-08-09 at 10 20 04 am" src="https://user-images.githubusercontent.com/1806894/43908560-e84878b8-9bbd-11e8-8300-45e2aa210091.png">

**Comment by valerybriz** [comment]
The library was removed from all the requirements
