### ISSUE TITLE
Add production deployment documentation

### ISSUE THREAD

**Issue by abisosa** [Prescrypto/WPCI#80]
- Dependencies
- Deployment steps (process)
- Any extra configuration if needed.
- Examples (heroku, digital ocean, etc)

**Comment by abisosa** [comment]
@ebarojas

**Comment by ebarojas** [comment]
FYI: We'll document this, but repo should install directly in a heroku instance integrated with Github.

**Comment by valerybriz** [comment]
You can find the documentation to initialize it here: https://github.com/Prescrypto/WPCI/wiki/Environment-Variables
and here:
https://www.wpci.io/docs
