### ISSUE TITLE
New endpoint to receive an external PDF link to create a document

### ISSUE THREAD

**Issue by valerybriz** [Prescrypto/WPCI#82]
create a new endpoint to receive a PDF file to create a document  
  
`Example Request: POST http://wpci-staging.herokuapp.com/api/v1/documents  
 Example Parameters: {   
  “doc_url”: “https://si.ua.es/es/documentos/documentacion/pdf-s/mozilla12-pdf.pdf”,  
  “doc_name”: “New Document”,  
  "render": "external"  
}  `

* doc_url = the url of the document (If external, this url most end with .pdf) else, it can be a google doc url
* doc name = is the name or title of the document
* render = is the source of the document (external = Any PDF url, google = google doc url)
* most be loggued to work.

**Comment by abisosa** [comment]
@valerybriz pregunta, este endpoint genera una copia del documento ? o sólo guarda el link?
Los links que enviaríamos nosotros tienen una expiración porque no pueden estar públicos.
Ayer generé un documento pero ahora no puedo verlo en wpci.
<img width="1436" alt="Screen Shot 2019-09-24 at 10 42 38 AM" src="https://user-images.githubusercontent.com/1024556/65527934-2013df00-deb9-11e9-9764-d3968bfefb44.png">

**Comment by valerybriz** [comment]
@abisosa este error es debido a que intenta descargar el pdf pero no lo logra esto aparece al intentar accesar al url que ingresaste para ese documento:
<img width="819" alt="Screen Shot 2019-09-24 at 11 23 56 AM" src="https://user-images.githubusercontent.com/22871092/65530715-15a81400-debe-11e9-8bdc-ca6dcce9c589.png">

**Comment by abisosa** [comment]
@valerybriz sí ese error sucede porque no podemos dejarlos públicos siempre pero entonces el workaround sería crear el documento, crear el link, firmar, descargar el resultado firmado en el instante y al final eliminar el documento y el link, cierto ?

**Comment by valerybriz** [comment]
> @valerybriz sí ese error sucede porque no podemos dejarlos públicos siempre pero entonces el workaround sería crear el documento, crear el link, firmar, descargar el resultado firmado en el instante y al final eliminar el documento y el link, cierto ?

Cierto, cabe resaltar que durante este proceso tendrían que dejar publico el documento.pdf(url) para que wpci pueda tener acceso.

La otra opción sería que lo creen como documento de google con acceso únicamente a su email registrado en wpci, entonces sería un documento privado al que wpci tendría acceso por medio de sus credenciales.

**Comment by valerybriz** [comment]
#90 este issue ya esta resuelto y en master
