### ISSUE TITLE
Agregar detalles adicionales al response de documents/signed

### ISSUE THREAD

**Issue by abisosa** [Prescrypto/WPCI#92]
@ebarojas @valerybriz 
Actualmente el response es:
```json
{"s3_contract_url": "https://wpci-staging.herokuapp.com/docs/view_sign_records/second.pdf_1569366025938_1"}
```

- Agregar `audit_url` y `signed_pdf_url` para obtener los documentos sin necesidad de visitar el dashboard de WPCI.

**Comment by valerybriz** [comment]
Este issue queda relacionado con el #95 que completa el flow de consumo de información del documento ya firmado, vamos a ponerlo en la cola de tasks :)

**Comment by ebarojas** [comment]
Duplicate #95
