### ISSUE TITLE
Hacer customizable el correo que se envía al usuario o tener la opción de desactivarlo.

### ISSUE THREAD

**Issue by abisosa** [Prescrypto/WPCI#93]
@ebarojas @valerybriz 
Actualmente los correos se ven así:
![Screen Shot 2019-09-25 at 11 41 17 AM](https://user-images.githubusercontent.com/1024556/65621470-6b95be00-df89-11e9-8f26-9bae403dadad.png)

Es posible hacerlos customizables para tener el branding de URBEM ahí ? Si no, entonces sería posible que tanto el correo de firma como el de descarga no se enviaran ?

**Comment by valerybriz** [comment]
@abisosa Nos podrías especificar un poco más que caracteristicas involucraría el brandind? (sender email, body in html, etc?)

**Comment by abisosa** [comment]
@valerybriz sorry typo: *branding**

Sería el body del html en colores y texto principalmente, sender email y subject.

**Comment by abisosa** [comment]
@valerybriz acá decidimos que sería mejor si tienen opción de desactivar el envío de correos y enviar nosotros el nuestro.

**Comment by valerybriz** [comment]
@abisosa De acuerdo, esto si es posible pero aun no esta desarrollado entonces vamos a añadirlo a la cola de tasks :)

**Comment by ebarojas** [comment]
*in progress* @abisosa

**Comment by valerybriz** [comment]
#98 lista la modificación @abisosa para poder deshabilitar el envio de emails al momento de firmar un documento solamente hay que agregar un parametro send_by_email = False
De la siguiente forma:
/api/v1/documents/signed/<LINK ID>?send_by_email=False 

para habilitarlo solo hay que cambiar ese flag a True o no enviar el parametro de send by email
