### ISSUE TITLE
Hacer costumizable la liga de verificación que se anexa al documento firmado

### ISSUE THREAD

**Issue by dherrera-civica** [Prescrypto/WPCI#94]
Comportamiento actual
- Cuando se firma un documento, se agrega la liga de Cryptosign al pdf generado que manda a la vista de validación del documento. 

Comportamiento deseado
- Esa liga debe poder ser costumizable para poder insertarla en el documento.

**Comment by dherrera-civica** [comment]
@ebarojas @valerybriz este issue lo hablamos la última vez para que la liga pudiera redireccionar a  la vista de validación de URBEM. 
Esta vista de validación consumiría los datos de validación de cryptosign y rexchain. Referencia issue #95 .

**Comment by valerybriz** [comment]
Una posible solución para esto @dherrera-civica sería proporcionarles el "address" de la transacción en rexchain y con este address (que en realidad es una especie de id) ustedes podrían consumir el api de rexchain y obtener todos los datos para crear su vista de validación, los datos que podrían obtener se verían algo así como esto: https://rexchain-staging.herokuapp.com/hash/5a0b26fb196a00ac32aa56fefc23c56e048163d5ebacdb85411180005b37da02/

**Comment by abisosa** [comment]
Gracias @valerybriz ! Me parece bien, tienes un ejemplo de la llamada al api de Rexchain ?

**Comment by valerybriz** [comment]
@abisosa Perdón por la tardanza en la respuesta, aquí está la documentación de rexchain para obtener el payload de una transacción: https://github.com/Prescrypto/RexChain/wiki/API-Endpoints
